# Generated by Django 4.1.2 on 2022-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('area', models.CharField(max_length=255, verbose_name='area')),
                ('cuisines', models.CharField(max_length=255, verbose_name='cuisines')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('cost_for_Two', models.BigIntegerField(verbose_name='costForTwo')),
                ('locality', models.CharField(max_length=25, verbose_name='locality')),
                ('avgRating', models.FloatField(max_length=25, verbose_name='avgRating')),
            ],
        ),
    ]
