# Generated by Django 4.1.2 on 2022-10-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='home_restaurant',
        ),
    ]
