# Generated by Django 4.1.2 on 2022-10-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_restaurant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(default='/static/images/dess1.png', upload_to='images/'),
        ),
    ]
