# Generated by Django 4.1.2 on 2022-10-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_rate_review_stars_remove_review_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='rest',
        ),
    ]
