# Generated by Django 4.1.2 on 2022-10-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_review_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rest',
            new_name='name',
        ),
    ]
