# Generated by Django 4.1.2 on 2022-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_rest_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='desciption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
