# Generated by Django 4.1.2 on 2022-10-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_restaurant_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='desciption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
